CREATE TABLE Part (
  idPart INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  mail VARCHAR(40) NOT NULL REFERENCES Investor(mail),
  idProject INTEGER NOT NULL REFERENCES Project(idProject),
  price FLOAT NOT NULL,
  date DATE NOT NULL
);